# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.29.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x1bplayerio.generated.messages\"\xc3\x01\n\x18\x46\x61\x63\x65\x62ookOAuthConnectArgs\x12\x0e\n\x06gameId\x18\x01 \x01(\t\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x02 \x01(\t\x12\x11\n\tpartnerId\x18\x03 \x01(\t\x12\x1d\n\x15playerInsightSegments\x18\x04 \x03(\t\x12\x11\n\tclientAPI\x18\x05 \x01(\t\x12=\n\nclientInfo\x18\x06 \x03(\x0b\x32).playerio.generated.messages.KeyValuePair\"\xba\x01\n\x1a\x46\x61\x63\x65\x62ookOAuthConnectOutput\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0e\n\x06userId\x18\x02 \x01(\t\x12\x1b\n\x0cshowBranding\x18\x03 \x01(\x08:\x05\x66\x61lse\x12\x19\n\x11gameFSRedirectMap\x18\x04 \x01(\t\x12\x16\n\x0e\x66\x61\x63\x65\x62ookUserId\x18\x05 \x01(\t\x12\x11\n\tpartnerId\x18\x06 \x01(\t\x12\x1a\n\x12playerInsightState\x18\x07 \x01(\t\"?\n\x19\x46\x61\x63\x65\x62ookOAuthConnectError\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\terrorCode\x18\x02 \x01(\x05\"*\n\x0cKeyValuePair\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\xd4\x01\n\x12\x43reateJoinRoomArgs\x12\x0e\n\x06roomId\x18\x01 \x01(\t\x12\x10\n\x08roomType\x18\x02 \x01(\t\x12\x0f\n\x07visible\x18\x03 \x01(\x08\x12;\n\x08roomData\x18\x04 \x03(\x0b\x32).playerio.generated.messages.KeyValuePair\x12;\n\x08joinData\x18\x05 \x03(\x0b\x32).playerio.generated.messages.KeyValuePair\x12\x11\n\tisDevRoom\x18\x06 \x01(\x08\"w\n\x14\x43reateJoinRoomOutput\x12\x0e\n\x06roomId\x18\x01 \x01(\t\x12\x0f\n\x07joinKey\x18\x02 \x01(\t\x12>\n\tendpoints\x18\x03 \x03(\x0b\x32+.playerio.generated.messages.ServerEndpoint\"9\n\x13\x43reateJoinRoomError\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\terrorCode\x18\x02 \x01(\x05\"/\n\x0eServerEndpoint\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FACEBOOKOAUTHCONNECTARGS']._serialized_start=44
  _globals['_FACEBOOKOAUTHCONNECTARGS']._serialized_end=239
  _globals['_FACEBOOKOAUTHCONNECTOUTPUT']._serialized_start=242
  _globals['_FACEBOOKOAUTHCONNECTOUTPUT']._serialized_end=428
  _globals['_FACEBOOKOAUTHCONNECTERROR']._serialized_start=430
  _globals['_FACEBOOKOAUTHCONNECTERROR']._serialized_end=493
  _globals['_KEYVALUEPAIR']._serialized_start=495
  _globals['_KEYVALUEPAIR']._serialized_end=537
  _globals['_CREATEJOINROOMARGS']._serialized_start=540
  _globals['_CREATEJOINROOMARGS']._serialized_end=752
  _globals['_CREATEJOINROOMOUTPUT']._serialized_start=754
  _globals['_CREATEJOINROOMOUTPUT']._serialized_end=873
  _globals['_CREATEJOINROOMERROR']._serialized_start=875
  _globals['_CREATEJOINROOMERROR']._serialized_end=932
  _globals['_SERVERENDPOINT']._serialized_start=934
  _globals['_SERVERENDPOINT']._serialized_end=981
# @@protoc_insertion_point(module_scope)
